### ISSUE TITLE
Change in EDIC page

### ISSUE THREAD

**Issue by learnwithparth** [learnwithparth/charusatv3#108]
Change the name to Jaimin Undavia, email address, phone no

**Comment by learnwithparth** [comment]
Remove endowment chair submenu from academic menu.

**Comment by learnwithparth** [comment]
Change the name of the submenu Academic Services to Students' Corner in the academics menu.

**Comment by learnwithparth** [comment]
Comment on the campus menu. Move Girls' hostel to the Admission menu under other information. Keep the submenu name Hostel only to make it general.

**Comment by learnwithparth** [comment]
Add the following URL of the laboratories video to the research menu:

https://youtu.be/Og4NMqI3q5M

**Comment by learnwithparth** [comment]
Add the following URL to Merit Scholarship (on the scholarship page) and fee details (on the front page).

https://drive.google.com/file/d/14qe_BKwzOQfK8M-yjN8YnYMAH4RcKHSS/view?usp=share_link

**Comment by learnwithparth** [comment]
Remove students' feed from About CHARUSAT

**Comment by learnwithparth** [comment]
Add the 12th convocation's details on the convocation page.

**Comment by learnwithparth** [comment]
remove the menu Name of Governing Member

**Comment by Jalpeshv** [comment]
> remove the menu Name of Governing Member

Updated

**Comment by Jalpeshv** [comment]
> > remove the menu Name of Governing Member
> 
> Updated

**Comment by ravichanga101** [comment]
> remove the menu Name of Governing Member



> https://youtu.be/Og4NMqI3q5M

done
